name: Generate Snake Contribution Graph

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake animation
        uses: Platane/snk@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: dist/snake.svg

      - name: Push Snake animation to output branch
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
